#!/bin/sh
set -e
#
# This script is meant for quick & easy install via:
#   'curl -sL https://raw.githubusercontent.com/Boukefalos/docker-deployment/master/setup | sh'
# or:
#   'wget -qO- https://raw.githubusercontent.com/Boukefalos/docker-deployment/master/setup | sh'

home=/etc/environment
url='https://get.docker.io/'

command_exists() {
	command -v "$@" > /dev/null 2>&1
}

if !command_exists docker; then
    echo Docker should be installed!
    exit 0
fi

curl=''
if command_exists curl; then
	curl='curl -sL'
elif command_exists wget; then
	curl='wget -qO-'
elif command_exists busybox && busybox --list-modules | grep -q wget; then
	curl='busybox wget -qO-'
fi